name: MoBoxDeathSwap
version: 1.0-SNAPSHOT
main: org.mossmc.mosscg.MoBoxDeathSwap.Main
author: MossCG
description: A plugin by MossCG for MoBoxMC.
softdepend: [MoBoxCore]
commands:
  moboxdeathswap:
    description: 主指令
  mbds:
    description: 主指令缩写
permissions:
  moboxdeathswap.help:
    description: 查看帮助权限
    default: true
  moboxdeathswap.resetcountdown:
    description: 重置等待时间权限
    default: op
  moboxdeathswap.reducecountdown:
    description: 减少等待时间权限
    default: op
  moboxdeathswap.changerole:
    description: 更换游戏角色权限
    default: op
  moboxdeathswap.changeotherrole:
    description: 更换他人游戏角色权限
    default: op
  moboxdeathswap.list:
    description: 查看游戏内玩家列表权限
    default: true